Numpy Assignment Questions

In [1]:
#Convert list to numpy array
list = [12.23, 13.32, 100, 36.32]
list

[12.23, 13.32, 100, 36.32]

In [2]:
import numpy as np

In [3]:
arr = np.array(list)
arr

array([ 12.23,  13.32, 100.  ,  36.32])

In [4]:
#Create 3*3 matrix with values form 2-10
arr = np.arange(2,11).reshape(3,3)
arr

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [5]:
#Make null vector and update 6th value to 11
arr = np.zeros(10)
arr[5]  = 11
arr

array([ 0.,  0.,  0.,  0.,  0., 11.,  0.,  0.,  0.,  0.])

In [6]:
#Write a python program to reverse array 
arr = np.arange(2,11)
rev = arr[::-1]
rev

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [7]:
#  create a 2d array with 1 on the border and 0 inside
arr = np.ones(25).reshape(5,5)
arr[1:-1 , 1:-1] = 0
arr


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
arr = np.zeros(25).reshape(5,5)
arr[1:-1,1:-1] = 1
arr

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

In [9]:
# create a 8x8 matrix and fill it with a checkerboard pattern.

arr = np.zeros((8,8))
arr[::2 , 1::2] = 1
arr[1::2 , ::2] = 1
arr


array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

In [10]:
#Tupule to array
tup = ((8, 4, 6), (1, 2, 3))
arr = np.array(tup)
arr

array([[8, 4, 6],
       [1, 2, 3]])

In [11]:
#append to array
arr = np.array([10,20,30])
arr

array([10, 20, 30])

In [12]:
np.append(arr,[40 ,50, 60, 70, 80, 90])

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [13]:
# Array separate real and imaginary array.
arr = np.array([1+0j, 0.70710678+0.70710678j])
arr

array([1.        +0.j        , 0.70710678+0.70710678j])

In [14]:

realarr = arr.real
print(realarr)

[1.         0.70710678]


In [15]:
imagpart = arr.imag
print(imagpart)

[0.         0.70710678]


In [16]:
#to find the number of elements of an array, length of one
import numpy as np

arr = np.array([10,20,30,40])
size = len(arr)
itemsize = arr.itemsize
print(itemsize)
print(size)
print("Total bytes = " , size*itemsize)

8
4
Total bytes =  32


In [17]:
# Find Common values between two arrays.
arr = np.array([0,10,20,30,40,60,])
prr = np.array([10,30,40,80,60])

commonvalues = np.intersect1d(arr , prr)
print(arr)
print(prr)
print(commonvalues)

[ 0 10 20 30 40 60]
[10 30 40 80 60]
[10 30 40 60]


In [18]:
#present in one set difference
arr = np.array([0,10,20,30,40,60,90,75,99])
prr = np.array([10,30,40,80,60])

ans = np.setdiff1d(arr,prr)
print(ans)

[ 0 20 75 90 99]


In [19]:
#present in one not both 

arr = np.array([0,10,20,30,40,60,90,75,99])
prr = np.array([10,30,40,80,60])

ans = np.setxor1d(arr,prr)
print(ans)

[ 0 20 75 80 90 99]


In [20]:
#Compare Arrays

import numpy as np

# Define arrays
a = np.array([1, 2])
b = np.array([4, 5])

# Comparisons
print("a > b")
print(a > b)

print("a >= b")
print(a >= b)

print("a < b")
print(a < b)

print("a <= b")
print(a <= b)

a > b
[False False]
a >= b
[False False]
a < b
[ True  True]
a <= b
[ True  True]


In [21]:
arr = np.array([10,20,30,40,50,60])

np.savetxt("array.txt", arr, fmt="%d")

print("Array saved to array.txt")

Array saved to array.txt


In [22]:
# Convert to flattened array
A = np.array([[1,2] , [3,4]])
A

array([[1, 2],
       [3, 4]])

In [23]:
arr = np.hstack(A)
arr

array([1, 2, 3, 4])

In [24]:
arr = arr.astype(float)
print("Data Type : " , arr.dtype)

Data Type :  float64


In [25]:
#create a 3-D array with ones on a diagonal and zeros elsewhere.

arr = np.identity(3)
arr 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [26]:
arr = np.tri(4,3)
arr

array([[1., 0., 0.],
       [1., 1., 0.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
import numpy as np

x = np.array([10,20,30,40])

x.flags.writeable = False

print("Now the array is read-only")

Now the array is read-only


In [33]:
arr = np.arange(0,12).reshape(3,4)
arr = arr*3
arr

array([[ 0,  3,  6,  9],
       [12, 15, 18, 21],
       [24, 27, 30, 33]])

In [34]:
listdata = arr.tolist()
listdata

[[0, 3, 6, 9], [12, 15, 18, 21], [24, 27, 30, 33]]

In [38]:
import numpy as np

arr = np.array([0.26153123, 0.52760141, 0.5718299, 0.5927067,
                0.7831874, 0.69746349, 0.35399976, 0.99469633,
                0.0694458, 0.54711478])

print("Original array elements:")
print(arr)

np.set_printoptions(precision=3)

print("Print array values with precision 3:")
print(arr)

Original array elements:
[0.26153123 0.52760141 0.5718299  0.5927067  0.7831874  0.69746349
 0.35399976 0.99469633 0.0694458  0.54711478]
Print array values with precision 3:
[0.262 0.528 0.572 0.593 0.783 0.697 0.354 0.995 0.069 0.547]


In [41]:
arr = np.array([1.6e-10, 1.6, 1200, 0.235])
print(arr)

np.set_printoptions(suppress=True,precision= 3)
arr

[1.60e-10 1.60e+00 1.20e+03 2.35e-01]


array([   0.   ,    1.6  , 1200.   ,    0.235])

In [43]:
# Original array
arr = np.array([[10, 20, 30],
                [40, 50, 60]])

col = np.array([200,400])

result = np.column_stack((arr , col))
print(result)

[[ 10  20  30 200]
 [ 40  50  60 400]]


In [44]:
# Original array
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

print("Original array:")
print(arr)

# Indices to delete → first(0), fourth(3), fifth(4)
result = np.delete(arr, [0, 3, 4])

print("Delete first, fourth and fifth elements:")
print(result)

Original array:
[ 10  20  30  40  50  60  70  80  90 100]
Delete first, fourth and fifth elements:
[ 20  30  60  70  80  90 100]
