In [293]:
import numpy as np

In [294]:
arr = np.array([1,2,3,4,5])

In [295]:
arr

array([1, 2, 3, 4, 5])

In [296]:
a = [1,2,3,4.5, "hello"]
a

[1, 2, 3, 4.5, 'hello']

In [297]:
np.array(a)


array(['1', '2', '3', '4.5', 'hello'], dtype='<U32')

In [298]:
np.array(a)

array(['1', '2', '3', '4.5', 'hello'], dtype='<U32')

In [299]:
l = [[1,2,3] , [4,5,6] , [7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [300]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [301]:
arr = np.arange(1,10,2)
arr

array([1, 3, 5, 7, 9])

In [302]:
arr =  np.zeros((4,6))
arr

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [303]:
arr  = np.ones((4,4))
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [304]:
#creates the linear spacing so that there is equal spaces between and 5 and there should be 3 numbers.
arr = np.linspace(1,5,4)
arr

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [305]:
arr = np.linspace(0 , 1 , 100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

__Random Generation function__

In [306]:
np.random.rand(5)

array([0.34946939, 0.23578152, 0.04171644, 0.11488246, 0.55796521])

In [307]:
np.random.randn(10)

array([ 0.72441145, -0.88583904,  0.01879428,  0.61346381,  0.69500421,
       -0.85560422, -0.64678113, -2.03128501, -0.28604498,  2.14538471])

In [308]:
np.random.randint(6)

3

In [309]:
np.random.randint(10,20)

12

Array Attributes

# Attributes are kind of variable that are defined inside a class
# Methods are some functions defined inside of class

In [310]:
arr = np.array([[1,2,3] , [4,5,6] , [7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [311]:
arr.shape

(3, 3)

In [312]:
arr.size

9

In [313]:
arr.dtype

dtype('int64')

# **Array Methods**

In [314]:

arr


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [315]:
arr.min()

np.int64(1)

In [316]:
arr.max()

np.int64(9)

In [317]:
arr.sum()

np.int64(45)

In [318]:
np.sum(arr,axis = 1)

array([ 6, 15, 24])

In [319]:
arr.mean()

np.float64(5.0)

In [320]:
arr.std()

np.float64(2.581988897471611)

In [321]:
arr.argmax()

np.int64(8)

In [322]:
arr.argmin()

np.int64(0)

In [323]:
#Reshaping and resizing

In [324]:
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [325]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

Numpy indexing and slicing of vectors


In [326]:
import numpy as np

In [327]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [328]:
arr[6]

np.int64(17)

In [329]:
arr[1:5]

array([12, 13, 14, 15])

In [245]:
arr_slice = arr[3::2]
arr_slice

array([14, 16, 18, 20])

In [246]:
arr[4]

np.int64(15)

Numpy Indexing and Slicing of Matrix

In [247]:
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [248]:
arr[0,0]

np.int64(1)

In [249]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [250]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

Boolean INdexing

In [251]:
arr = np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [252]:
bool_index = arr%2== 0

In [253]:
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [254]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

Arithmatic operations

In [255]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

In [256]:
arr3 = arr1 + arr2
arr3

array([ 7,  9, 11, 13, 15])

In [257]:
arr1 - arr2

array([-5, -5, -5, -5, -5])

In [258]:
arr1 * arr2

array([ 6, 14, 24, 36, 50])

In [259]:
arr1/arr2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

Broadcasting


In [260]:
l = [10,20,30,40,50]
arr = np.array(l)

In [261]:
arr + 10

array([20, 30, 40, 50, 60])

In [262]:
arr = np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [263]:
arr + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [264]:
arr = np.arange(1,26) 
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [265]:
b = arr.copy()
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [266]:
b[0] = 100
b

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25])

In [267]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [268]:
A = np.array([[1,2] , [3,4]])
B = np.array([[5,6],[7,8]])

In [269]:
A

array([[1, 2],
       [3, 4]])

In [270]:
B

array([[5, 6],
       [7, 8]])

In [271]:
A*B

array([[ 5, 12],
       [21, 32]])

In [272]:
A @ B

array([[19, 22],
       [43, 50]])

In [273]:
A.T

array([[1, 3],
       [2, 4]])

Advance Array Manipulation 
Stacking Array

In [274]:
A

array([[1, 2],
       [3, 4]])

In [275]:
B

array([[5, 6],
       [7, 8]])

In [276]:
a = np.arange(1,5)
b = np.arange(5,9)


In [277]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [278]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [279]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [280]:
import numpy as np

In [281]:
# for i in range(0,9,3):
#     for j in range(0,9,3):
#         n = s[i:i+3, j+3]
#         print(n.sum())


In [282]:
data = np.array([
    [18,85,78],
    [19,92,88],
    [17,76,95],
    [18,65,70],
    [20,19,85],
])

In [283]:
data.shape

(5, 3)

In [284]:
ans = np.mean(data[:,0])
ans

np.float64(18.4)

In [285]:
data[:,1]

array([85, 92, 76, 65, 19])

In [286]:
np.max(data[:,2])

np.int64(95)

In [287]:
data[data[:,1] > 90]

array([[19, 92, 88]])

In [288]:
data[:,1] += 5


In [289]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 24, 85]])

In [290]:
len(data[data[:,0] < 19])

3

In [291]:
np.mean(data[:,1:],axis=0)

array([72.4, 83.2])

In [292]:
data[(data[:,1] >= 80) & (data[:,2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95]])

In [330]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 24, 85]])

In [335]:
data[:,2][data[:,2] <= 75] = 0

In [336]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [ 0,  0,  0],
       [20, 24, 85]])